### ISSUE TITLE
The link of the kitti bag

### ISSUE THREAD

**Issue by LeiXu1999** [StephLin/LIO-SEGMOT#10]
Hi，
I can't download the kitti bag. Can you provide another link？such as Baidu Cloud？
Thanks

**Comment by StephLin** [comment]
Hi @LeiXu1999 ,

Sorry for the late reply. Could you download the sample dataset (KITTI) with the following link: 

https://drive.google.com/drive/folders/1RLlUKq8uiro6-5HY6m3lVcppJxYDuNAX?usp=share_link

Thank you!

**Comment by LeiXu1999** [comment]
Thank you very much, I have one more question. The SE-SSD detects well on the kitti dataset, but  it gives detection errors on the 16-lines lidar, have you encountered this problem?

**Comment by StephLin** [comment]
Unfortunately, I do not try SE-SSD detector on other 16-beam LiDAR scanners. Does the _detection error_ mean that there is an unexpected (programmatic) exception raised? If so, can you provide more information so that I can (try my best to) figure out something wrong on your cases.

Or, do you mean there are some false positive detections? If so, I suggest you ask [SE-SSD's authors](https://github.com/Vegeta2020/SE-SSD) for such detection performance issues :)
