### ISSUE TITLE
A problem for the project "livox_detection_lio_segmot".

### ISSUE THREAD

**Issue by BIT-wangzb** [StephLin/LIO-SEGMOT#12]
When I run ros_main.py in _livox_detection_lio_segmot_, I got an error: _No module named 'lio_segmot'_. I have read the _readme.md_ of _livox_detection_lio_segmot_. It didn't help me solve the problem. How can I fix it.?

**Comment by StephLin** [comment]
Hi @BIT-wangzb,

It means that Python cannot find `lio_segmot`'s ros messages. You can check if LIO-SEGMOT is compiled and you can import `lio_segmot` in Python.

There are two ways to check your environment based on your setup method. If you setup `livox_detection_lio_segmot` without Docker, you may need to configure `PYTHONPATH` so that the detection's Python interpreter can find the `lio_segmot` module. Otherwise, you can check if [the first volume in `docker-compose.yml`](https://github.com/StephLin/livox_detection_lio_segmot/blob/detection_v1.1_lio_segmot/docker-compose.yml#L7) is correctly configured. The path before colon should be the absolute path to the `lio_segmot`'s module.

**Comment by BIT-wangzb** [comment]
> Hi @BIT-wangzb,
> 
> It means that Python cannot find `lio_segmot`'s ros messages. You can check if LIO-SEGMOT is compiled and you can import `lio_segmot` in Python.
> 
> There are two ways to check your environment based on your setup method. If you setup `livox_detection_lio_segmot` without Docker, you may need to configure `PYTHONPATH` so that the detection's Python interpreter can find the `lio_segmot` module. Otherwise, you can check if [the first volume in `docker-compose.yml`](https://github.com/StephLin/livox_detection_lio_segmot/blob/detection_v1.1_lio_segmot/docker-compose.yml#L7) is correctly configured. The path before colon should be the absolute path to the `lio_segmot`'s module.

Hi @StephLin,
Thank you for your response. I have fixed the problem by configuring `PYTHONPATH` and `source .../lio_segmot_ros/devel/setup.bash`.

**Comment by sdhuaiyj** [comment]
Hi @BIT-wangzb,
You mentioned in the paper A Robot Planar Marker-Based Visual SLAM that the code will be open source. Have you opened the code yet. If possible, I would be very grateful.

**Comment by BIT-wangzb** [comment]
> 

I have re-open sourced the project and you can find it at _https://github.com/BIT-wangzb/Marker-based-SLAM_.
