### ISSUE TITLE
Livox Detector for segmot using Cuda

### ISSUE THREAD

**Issue by mantruong204** [StephLin/LIO-SEGMOT#18]
Thanks for a great work, StephLin!
I found out that the original livox_detection ([https://github.com/Livox-SDK/livox_detection](livox_detection)) is able to utilize Cuda to accelerate the computation. The average computation time per frame of it is just ~190ms. 
However, I can not config the livox_segmot detector to do the same thing. Livox_segmot is running on CPU and takes ~900ms per a frame. Could you please give instruction to config livox_segmot detector to running on Cuda?

**Comment by StephLin** [comment]
Hi @mantruong204,

It's worth noting that [the latest Livox detector](https://github.com/Livox-SDK/livox_detection) uses Pytorch 1.8+ instead of TF 1.13+, which is used in [LIO-SEGMOT's forked version](https://github.com/StephLin/livox_detection_lio_segmot). 

To run our forked version with GPU, you can check if your GPU is available, and Tensorflow package is also built with cuda:

```python
import tensorflow as tf

print("GPU available:", tf.test.is_gpu_available())
print("TF-CUDA:", tf.test.is_built_with_cuda())
```

**Comment by mantruong204** [comment]
Thanks @StephLin ,
I have tried rebuild my tensorflow with cuda and it is working now.
